version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: menekel_api
    ports:
      - 9191:9090
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app
  mysql:
    image: mysql:5.7 
    container_name: menekel_mysql
    command: mysqld --user=root
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=article
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10